title: ICT Security
description: >- # this means to ignore newlines until "baseurl:"
  Dit is de website behorende bij de uitgave 'ICT Security' van Boris Sondagh.
  Deze website bevat onder andere bestanden, werkbladen en tools.
github_username:  botris

# Build settings
theme: jekyll-theme-minimal

show_downloads: true
