title: ICT Security
description: >- # this means to ignore newlines until "baseurl:"
  Methodewebsite voor het boek "ICT Security; praktische beveiliging van computersystemen, digitale media en netwerkverbindingen".
github_username:  botris

# Build settings
theme: jekyll-theme-minimal

show_downloads: false

collections:
  hoofdstukken:
    output: true

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from